input {
  http {
    port => 5000
    codec => json
  }
}

filter {
  # Dacă nu există un timestamp, adăugăm unul bazat pe timpul curent
  if ![timestamp] {
    mutate {
      add_field => {
        "timestamp" => "%{@timestamp}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ecommerce-logs-%{+YYYY.MM.dd}"
  }

  # Afișează logurile și în consolă pentru debugging
  stdout {
    codec => rubydebug
  }
}
